CREATE TABLE IF NOT EXISTS `sys_log` (
    `id` bigint NOT NULL,
    `user_id` bigint DEFAULT NULL,
    `username` varchar(50) DEFAULT NULL,
    `real_name` varchar(50) DEFAULT NULL,
    `module` varchar(100) DEFAULT NULL,
    `action` varchar(100) DEFAULT NULL,
    `target` varchar(500) DEFAULT NULL,
    `target_id` bigint DEFAULT NULL,
    `request_method` varchar(10) DEFAULT NULL,
    `request_url` varchar(500) DEFAULT NULL,
    `request_params` text,
    `result` varchar(20) DEFAULT NULL,
    `error_msg` text,
    `cost_time` bigint DEFAULT NULL,
    `ip` varchar(50) DEFAULT NULL,
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_module` (`module`),
    KEY `idx_action` (`action`),
    KEY `idx_result` (`result`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_ip` (`ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';